language: csharp
mono: none
dotnet: 1.1.0
dist: trusty
script:
 - dotnet restore
 - dotnet pack -c Release -o ..
 - dotnet nuget push MygetCITestCore.1.0.0.nupkg -k 79fed081-43ff-437a-8520-a8368a52b6ba -s https://www.myget.org/F/dota2/api/v2/package
